# Generated by Django 4.0.4 on 2022-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('summoner_id', models.CharField(max_length=63)),
                ('puuid', models.CharField(max_length=78, null=True)),
                ('level', models.IntegerField()),
                ('tier', models.CharField(max_length=3, null=True)),
                ('rank', models.CharField(max_length=11, null=True)),
                ('lp', models.IntegerField(null=True)),
                ('hotstreak', models.BooleanField(null=True)),
                ('divinity', models.BooleanField(null=True)),
            ],
        ),
    ]
