# Generated by Django 4.1.1 on 2022-09-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiotAPICalls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='divinity',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='hotstreak',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='level',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='lp',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='puuid',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='summoner_id',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='tier',
        ),
    ]
